In [4]:
from clase import cuartas 
from clasificacion_solo4 import *
from clasificacion import *
import glob 
import os
import music21

/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.0.4) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

In [5]:
xml_file = '../Archivos/Corales/corales_completo/024864Bs.xml'
# xml_file = '../Archivos/Corales/corales_completo/024511B_.xml'

/home/cuba/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "

In [14]:
solo4 = cuartas(xml_file)
df_4 = solo4.extraer_df()

In [24]:
ind, df_fil4  = encontrar_4(df_4)

In [25]:
df_fil4 = df_fil4.rename(columns={'Notas': 'Acordes'})
df_fil4

,Acordes,Intervalos,Nombre intervalo simplificado,Num_semitonos,Nombre intervalo completo,Beat,Comp치s,Duraci칩n,Tipo
6,"['A3', 'D4', 'F#4']","[6, 4]","[P4, M6]","[5, 9]","[Perfect Fourth, Major Sixth]",4.0,1,1.00,quarter
9,"['E3', 'A3', 'C#4', 'E4']","[8, 6, 4]","[P4, M6, P8]","[5, 9, 12]","[Perfect Fourth, Major Sixth, Perfect Octave]",2.0,2,0.50,eighth
14,"['F#3', 'F#4', 'B4', 'D5']","[8, 6, 4]","[P8, P4, m6]","[12, 17, 20]","[Perfect Octave, Perfect Fourth, Minor Sixth]",1.5,3,0.50,eighth
30,"['A3', 'D4', 'F#4']","[6, 4]","[P4, M6]","[5, 9]","[Perfect Fourth, Major Sixth]",4.0,5,1.00,quarter
33,"['E3', 'A3', 'C#4', 'E4']","[8, 6, 4]","[P4, M6, P8]","[5, 9, 12]","[Perfect Fourth, Major Sixth, Perfect Octave]",2.0,6,0.50,eighth
38,"['F#3', 'F#4', 'B4', 'D5']","[8, 6, 4]","[P8, P4, m6]","[12, 17, 20]","[Perfect Octave, Perfect Fourth, Minor Sixth]",1.5,7,0.50,eighth
48,"['A3', 'E4', 'B4', 'D5']","[5, 4, 2]","[P5, M2, P4]","[7, 14, 17]","[Perfect Fifth, Major Second, Perfect Fourth]",4.0,8,0.50,eighth
53,"['D3', 'D4', 'G4', 'A4']","[8, 5, 4]","[P8, P4, P5]","[12, 17, 19]","[Perfect Octave, Perfect Fourth, Perfect Fifth]",2.5,9,0.25,16th
56,"['F#3', 'D4', 'G4', 'B4']","[6, 4, 2]","[m6, m2, P4]","[8, 13, 17]","[Minor Sixth, Minor Second, Perfect Fourth]",3.5,9,0.50,eighth
60,"['A3', 'D4', 'F#4', 'D5']","[6, 4, 4]","[P4, M6, P4]","[5, 9, 17]","[Perfect Fourth, Major Sixth, Perfect Fourth]",1.5,10,0.50,eighth
92,"['A3', 'D4', 'E4']","[5, 4]","[P4, P5]","[5, 7]","[Perfect Fourth, Perfect Fifth]",3.0,15,0.50,eighth

In [26]:
df_fil4['Solo 4tas'] = '1'

#Solo columnas de interes 

df_fil4 = df_fil4[['Acordes','Solo 4tas']]

In [27]:
df_estoy = dataframe_clasificacion(df_4)

KeyError: 'Notas'

In [32]:
df_nuevo = pd.DataFrame


#acordes a string

df_fil4 =acordes_to_string(df_fil4)

df_nuevo = pd.merge(df_estoy, df_fil4, on='Acordes', how='right')

/home/cuba/Documents/UNIVERSIDAD/M_C/Notebooks/clasificacion.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Acordes'] = df['Acordes'].apply(lambda x: str(x) if isinstance(x, list) else x)

In [37]:
df_nuevo.drop_duplicates()

,Acordes,Comp치s,Beat,Duraci칩n,Suma_paso (n/4),Suma_cadencial (n/4),Suma_bordadura (n/3),Clasificaci칩n,Solo 4tas
0,"['A3', 'D4', 'F#4']",1.0,4.0,1.0,2.0,1.0,0.0,NI,1
8,"['A3', 'D4', 'F#4']",5.0,4.0,1.0,2.0,1.0,0.0,NI,1
16,"['E3', 'A3', 'C#4', 'E4']",2.0,2.0,0.5,0.0,1.0,0.0,NI,1
24,"['E3', 'A3', 'C#4', 'E4']",6.0,2.0,0.5,0.0,1.0,0.0,NI,1
32,"['F#3', 'F#4', 'B4', 'D5']",3.0,1.5,0.5,2.0,1.0,0.0,NI,1
40,"['F#3', 'F#4', 'B4', 'D5']",7.0,1.5,0.5,2.0,1.0,0.0,NI,1
96,"['A3', 'E4', 'B4', 'D5']",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
97,"['D3', 'D4', 'G4', 'A4']",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
98,"['F#3', 'D4', 'G4', 'B4']",9.0,3.5,0.5,3.0,1.0,0.0,NI,1
99,"['A3', 'D4', 'F#4', 'D5']",10.0,1.5,0.5,3.0,1.0,0.0,NI,1
100,"['A3', 'D4', 'E4']",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1